import flet as ft
from views.PersonajeDetalle import PersonajeDetalle

PERSONAJES = [
    {"nombre": "Jean",  "imagen": "Jean.jpg", "region": "Mondstadt", "elemento": "Anemo", "rol": "Healer/Suport", "reacciones": "Torbellinos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Venti",  "imagen": "Venti.jpg", "region": "Mondstadt", "elemento": "Anemo", "rol": "Suport/Sub dps", "reacciones": "Torbellinos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Sacarosa",  "imagen": "Sacarosa.jpg", "region": "Mondstadt", "elemento": "Anemo", "rol": "Suport", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Varka",  "imagen": "Varka.jpg", "region": "Mondstadt", "elemento": "Anemo", "rol": "Main dps", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Prune",  "imagen": "Prune.jpg", "region": "Mondstadt", "elemento": "Anemo", "rol": "Suport/Buffer", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Xiao",  "imagen": "Xiao.jpg", "region": "Liyue", "elemento": "Anemo", "rol": "Main dps", "reacciones": "Torbellinos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Xianyun",  "imagen": "Xianyun.jpg", "region": "Liyue", "elemento": "Anemo", "rol": "Buffer", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Lan Yan",  "imagen": "Lanyan.jpg", "region": "Liyue", "elemento": "Anemo", "rol": "Escudo", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Kaedehara Kazuha",  "imagen": "Kazuha.jpg", "region": "Inazuma", "elemento": "Anemo", "rol": "Suport", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Ataque Básico > Habilidad Definitiva", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Sayu", "imagen": "Sayu.jpg", "region": "Inazuma", "elemento": "Anemo", "rol": "Suport", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Shikanoin Heizou", "imagen": "Heizou.jpg", "region": "Inazuma", "elemento": "Anemo", "rol": "Main dps", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Yumemizuki Mizuki", "imagen": "Mizuki.jpg", "region": "Inazuma", "elemento": "Anemo", "rol": "Suport/Sub dps", "reacciones": "Torbellinos", "talentos": "Ataque Básico > Habilidad Elemental > Habilidad Definitiva", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Trotamundos", "imagen": "Trotamundos.jpg", "region": "Dudosa Precedencia", "elemento": "Anemo", "rol": "Main dps", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Faruzán", "imagen": "Faruzan.jpg", "region": "Sumeru", "elemento": "Anemo", "rol": "Buffer", "reacciones": "Torbellinos", "talentos": "Ataque Básico > Habilidad Definitiva > Habilidad Elemental", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Lynette", "imagen": "Lynette.jpg", "region": "Fontaine", "elemento": "Anemo", "rol": "Suport", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Chasca", "imagen": "Chasca.jpg", "region": "Natlan", "elemento": "Anemo", "rol": "Main dps", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Ifá", "imagen": "Ifa.jpg", "region": "Natlan", "elemento": "Anemo", "rol": "Main dps/Healer", "reacciones": "Torbellinos", "talentos": "text", "estadisticas": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Jahoda", "imagen": "Jahoda.jpg", "region": "Nod Krai", "elemento": "Anemo", "rol": "Suport", "reacciones": "Torbellinos", "talentos": "Ataque Básico > Habilidad Definitiva > Habilidad Elemental", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
]


def AnemoView(page: ft.Page, user: dict, on_volver=None):
    from views.pyros import _ElementoView
    return _ElementoView(page, user, on_volver, "Anemo", "#6ee7b7", PERSONAJES)
