import flet as ft
from views.PersonajeDetalle import PersonajeDetalle

PERSONAJES = [
    {"nombre": "Jean",  "imagen": "Jean.jpg", "region": "Mondstadt", "elemento": "Anemo", "rol": "Healer/Suport", "reacciones": "Torbellinos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["SombraVerde.webp","RitualDeLaNobleza.webp","PerlaOceanica.webp"], "equipos": [["Kokomi.jpg","Beidou.jpg","Fischl.jpg","Jean.jpg"],["Ayato.jpg","Furina.jpg","Yunjin.jpg","Jean.jpg"],["Diluc.jpg","Xingchiu.jpg","Xiangling.jpg","Jean.jpg"]], "armas5": ["Objeto_Aquila_Favonia.webp","Objeto_Hoja_Afilada_Celestial.webp","Objeto_Cortador_de_Jade_Primordial.webp"], "armas4": ["Objeto_Espada_de_Favonius.webp","DeseoPonsoñoso.webp","Amenoma.webp"]},
    {"nombre": "Venti",  "imagen": "Venti.jpg", "region": "Mondstadt", "elemento": "Anemo", "rol": "Suport/Sub dps", "reacciones": "Torbellinos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["SombraVerde.webp","DiadelosVientos.webp","RitualDeLaNobleza.webp"], "equipos": [["Neuvillette.jpg","Furina.jpg","Xilonen.jpg","Venti.jpg"],["Mavuika.jpg","Citlali.jpg","Bennett.jpg","Venti.jpg"],["Mona.jpg","Diona.jpg","Ganyu.jpg","Venti.jpg"]], "armas5": ["Albores.webp","EstrellaInvernal.webp","Buitreastral.webp"], "armas4": ["Objeto_Arco_del_Sacrificio.webp","Objeto_Arco_de_Favonius.webp","Objeto_Ultimo_Acorde.webp"]},
    {"nombre": "Sacarosa",  "imagen": "Sacarosa.jpg", "region": "Mondstadt", "elemento": "Anemo", "rol": "Suport", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["SombraVerde.webp","Instructor.webp","OrquestaErrante.webp"], "equipos": [["Flins.jpg","Aino.jpg","Ineffa.jpg","Sacarosa.jpg"],["Nefer.jpg","Lauma.jpg","Aino.jpg","Sacarosa.jpg"],["Arle.jpg","Citlali.jpg","Bennett.jpg","Sacarosa.jpg"]], "armas5": ["MilNoches.webp","Hibernacion.webp","Tejenoches.webp"], "armas4": ["EstrellaErrabunda.webp","MemoriasdeSacrificios.webp","Hakushin.webp"]},
    {"nombre": "Varka",  "imagen": "Varka.jpg", "region": "Mondstadt", "elemento": "Anemo", "rol": "Main dps", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["DiadelosVientos.webp","SombraVerde.webp","Gladiador.webp"], "equipos": [["Ifa.jpg","Durin.jpg","Bennett.jpg","Varka.jpg"],["Faruzan.jpg","Durin.jpg","Bennett.jpg","Varka.jpg"],["Sacarosa.jpg","Bennett.jpg","Chevreuse.jpg","Varka.jpg"]], "armas5": ["CantardelLobo.","MardeJuncos.webp","LapidadelLobo.webp"], "armas4": ["MeduladelaSerpiente.webp","SombradelaMarea.webp","GranEspadaSacrificio.webp"]},
    {"nombre": "Prune",  "imagen": "Prune.jpg", "region": "Mondstadt", "elemento": "Anemo", "rol": "Suport/Buffer", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["DiadelosVientos.webp","SombraVerde.webp","OrquestaErrante.webp"], "equipos": [["Nicole.jpg","Prune.jpg","Durin.jpg","Varka.jpg"],["Durin.jpg","Prune.jpg","Nicole.jpg","Clorinde.jpg"],["Durin.jpg","Prune.jpg","Faruzan.jpg","Varka.jpg"]], "armas5": ["MilNoches.webp","Hibernacion.webp","Tejenoches.webp"], "armas4": ["EstrellaErrabunda.webp","MemoriasdeSacrificios.webp","Hakushin.webp"]},
    {"nombre": "Xiao",  "imagen": "Xiao.jpg", "region": "Liyue", "elemento": "Anemo", "rol": "Main dps", "reacciones": "Torbellinos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["CazadorFantasmal.webp","Cinabrio.webp","JuramentodelaNoche.webp"], "equipos": [["Xiao.jpg","Faruzan.jpg","Bennett.jpg","Zhongli.jpg"],["Xiao.jpg","Faruzan.jpg","Yelan.jpg","Bennett.jpg"],["Xiao.jpg","Jean.jpg","Albedo.jpg","Zhongli.jpg"]], "armas5": ["HaloFracturado.webp","Homa.webp","Halcon.webp"], "armas4": ["LanzadelDuelo.webp","LanzaPeñascoOscuro.webp","CharlaPabellon.webp"]},
    {"nombre": "Xianyun",  "imagen": "Xianyun.jpg", "region": "Liyue", "elemento": "Anemo", "rol": "Buffer", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["SombraVerde.webp","RitualDeLaNobleza.webp","PerlaOceanica.webp"], "equipos": [["Xiao.jpg","Faruzan.jpg","Furina.jpg","Xianyun.jpg"],["Xiao.jpg","Faruzan.jpg","Bennett.jpg","Xianyun.jpg"],["Gaming.jpg","Ganyu.jpg","Layla.jpg","Xianyun.jpg"]], "armas5": ["PergaminoCelestial.webp","ReverberacionGrulla.webp","OracionPerdida.webp"], "armas4": ["CodicedeFavonius.webp","OjodelJuramento.webp","FluenciaImpoluta.webp"]},
    {"nombre": "Lan Yan",  "imagen": "Lanyan.jpg", "region": "Liyue", "elemento": "Anemo", "rol": "Escudo", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["SombraVerde.webp","Gladiador.webp","OrquestaErrante.webp"], "equipos": [["Lanyan.jpg","Faruzan.jpg","Furina.jpg","Xianyun.jpg"],["Lanyan.jpg","Citlali.jpg","Furina.jpg","Bennett.jpg"],["Lanyan.jpg","Mualani.jpg","Xilonen.jpg","Xiangling.jpg"]], "armas5": ["PergaminoCelestial.webp","ReverberacionGrulla.webp","OracionPerdida.webp"], "armas4": ["MemoriasdeSacrificios.webp","SinfoniadelosMerodeadores.webp","OjodelaPerspicasia.webp"]},
    {"nombre": "Kaedehara Kazuha",  "imagen": "Kazuha.jpg", "region": "Inazuma", "elemento": "Anemo", "rol": "Suport", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Ataque Básico > Habilidad Definitiva", "estadisticas": "text", "artefactos": ["SombraVerde.webp","FuriadelTrueno.webp","RitualDeLaNobleza.webp"], "equipos": [["Yelan.jpg","Furina.jpg","Sigewinne.jpg","Kazuha.jpg"],["Clorinde.jpg","Fischl.jpg","Nahida.jpg","Kazuha.jpg"],["Tartaglia","Xiangling.jpg","Bennett.jpg","Kazuha.jpg"]], "armas5": ["JuramentoporlaLibertad.webp","Objeto_Hoja_Afilada_Celestial.webp","Objeto_Aquila_Favonia.webp"], "armas4": ["EspinadeHierro.webp","Xifos.webp","Objeto_Espada_de_Favonius.webp"]},
    {"nombre": "Sayu", "imagen": "Sayu.jpg", "region": "Inazuma", "elemento": "Anemo", "rol": "Suport", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["SombraVerde.webp","RitualDeLaNobleza.webp","PerlaOceanica.webp"], "equipos": [["Xiao.jpg","Chongyun,jpg","Zhongli.jpg","Sayu.jpg"],["Xiangling.jpg","Albedo.jpg","Zhongli.jpg","Sayu.jpg"],["HuTao.jpg","Zhongli.jpg","Xingchiu.jpg","Sayu.jpg"]], "armas5": ["LapidadelLobo.webp","OrgulloCelestial.webp","MardeJuncos.webp"], "armas4": ["GranEspadadeFavonius.webp","GranEspadaSacrificio.webp","SegadoradelaLluvia.webp"]},
    {"nombre": "Shikanoin Heizou", "imagen": "Heizou.jpg", "region": "Inazuma", "elemento": "Anemo", "rol": "Main dps", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["SombraVerde.webp","CompañiaDorada.webp","Gladiador.webp"], "equipos": [["Heizou.jpg","Faruzan.jpg","Yelan.jpg","Bennett.jpg"],["Heizou.jpg","Xingchiu.jpg","Xiangling.jpg","Bennett.jpg"],["Heizou.jpg","Yelan.jpg","Xiangling.jpg","Bennett.jpg"]], "armas5": ["AxiomadelaKagura.webp","PergaminoCelestial.webp","OracionPerdida.webp"], "armas4": ["SinfoniadelosMerodeadores.webp","PerlaSolar.webp","CartaNautica.webp"]},
    {"nombre": "Yumemizuki Mizuki", "imagen": "Mizuki.jpg", "region": "Inazuma", "elemento": "Anemo", "rol": "Suport/Sub dps", "reacciones": "Torbellinos", "talentos": "Ataque Básico > Habilidad Elemental > Habilidad Definitiva", "estadisticas": "text", "artefactos": ["SombraVerde.webp","OrquestaErrante.webp","SueñosAureos.webp"], "equipos": [["Mizuki.jpg","Furina.jpg","Ororon.jpg","Venti.jpg"],["Mizuki.jpg","Furina.jpg","Mavuika.jpg","Venti.jpg"],["Mizuki.jpg","Citlali.jpg","Mavuika.jpg","Venti.jpg"]], "armas5": ["Hibernacion.webp","VigiadelasEstrellas.webp","MilNoches.webp"], "armas4": ["MemoriasdeSacrificios.webp","CartaNautica.webp","Laud.webp"]},
    {"nombre": "Trotamundos", "imagen": "Trotamundos.jpg", "region": "Dudosa Precedencia", "elemento": "Anemo", "rol": "Main dps", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["Pabellon.webp","Reminiscencia.webp","EcodelSacrificio.webp"], "equipos": [["Trotamundos.jpg","Xiangling.jpg","Xingchiu.jpg","Bennett.jpg"],["Trotamundos.jpg","Faruzan.jpg","Xingchiu.jpg","Bennett.jpg"],["Trotamundos.jpg","Faruzan.jpg","Yelan.jpg","Bennett.jpg"]], "armas5": ["Tulaytulah.webp","CandadoTerrenal.webp","PergaminoCelestial.webp"], "armas4": ["SinfoniadelosMerodeadores.webp","PerlaSolar.webp","OjodelaPerspicasia.webp"]},
    {"nombre": "Faruzán", "imagen": "Faruzan.jpg", "region": "Sumeru", "elemento": "Anemo", "rol": "Buffer", "reacciones": "Torbellinos", "talentos": "Ataque Básico > Habilidad Definitiva > Habilidad Elemental", "estadisticas": "text", "artefactos": ["RitualDeLaNobleza.webp","PergaminoHeroe.webp","SombraVerde.webp"], "equipos": [["Trotamundos.jpg","Xingchiu.jpg","Bennett.jpg","Faruzan.jpg"],["Trotamundos.jpg","Yelan.jpg","Bennett.jpg","Faruzan.jpg"],["Trotamundos.jpg","Rosaria.jpg","Bennett.jpg","Faruzan.jpg"]], "armas5": ["AlasCelestiales.webp","ElegiadelFin.webp","EstrellaInvernal.webp"], "armas4": ["Objeto_Arco_de_Favonius.webp","FindelasAguas.webp","Objeto_Arco_del_Sacrificio.webp"]},
    {"nombre": "Lynette", "imagen": "Lynette.jpg", "region": "Fontaine", "elemento": "Anemo", "rol": "Suport", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Chasca", "imagen": "Chasca.jpg", "region": "Natlan", "elemento": "Anemo", "rol": "Main dps", "reacciones": "Torbellinos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Ifá", "imagen": "Ifa.jpg", "region": "Natlan", "elemento": "Anemo", "rol": "Main dps/Healer", "reacciones": "Torbellinos", "talentos": "text", "estadisticas": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Jahoda", "imagen": "Jahoda.jpg", "region": "Nod Krai", "elemento": "Anemo", "rol": "Suport", "reacciones": "Torbellinos", "talentos": "Ataque Básico > Habilidad Definitiva > Habilidad Elemental", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
]


def AnemoView(page: ft.Page, user: dict, on_volver=None):
    from views.pyros import _ElementoView
    return _ElementoView(page, user, on_volver, "Anemo", "#6ee7b7", PERSONAJES)
