import flet as ft
from views.PersonajeDetalle import PersonajeDetalle

PERSONAJES = [
    {"nombre": "Kaeya",  "imagen": "Kaeya.jpg", "region": "Mondstadt", "rol": "Sub dps", "elemento": "Cryo", "reacciones": "Congelados/Derretidos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["NomadaDelInvierno.webp","EmblemadelDestino.webp","RitualDeLaNobleza.webp"], "equipos": [["HuTao.jpg","Kaeya.jpg","Xingchiu.jpg","Zhongli.jpg"],["Chongyun.jpg","Kaeya.jpg","Xiangling.jpg","Bennett.jpg"],["Ayaka.jpg","Kaeya.jpg","Venti.jpg","Ayaka.jpg"]], "armas5": ["Objeto_Aquila_Favonia.webp","ReflejodelasTinieblas.webp","Objeto_Hoja_Afilada_Celestial.webp"], "armas4": ["Objeto_Espada_de_Favonius.webp","Requiem_Abisal.webp","EspinadeHierro.jpg"]},
    {"nombre": "Diona",  "imagen": "Diona.jpg", "region": "Mondstadt", "rol": "Escudo/Healer", "elemento": "Cryo", "reacciones": "Congelados/Superconductor", "talentos": "Habilidaad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["RitualDeLaNobleza.webp","PergaminoHeroe.webp","PerlaOceanica.webp"], "equipos": [["HuTao.jpg","Xingchiu.jpg","Rosaria.jpg","Diona.jpg"],["Ayaka.jpg","Kazuha.jpg","Kokomi.jpg","Diona.jpg"],["Ayaka.jpg","Mona.jpg","Venti.jpg","Diona.jpg"]], "armas5": ["ElegiadelFin.webp","CorazondelaLluvia.webp","EstrellaInvernal.webp"], "armas4": ["Objeto_Arco_de_Favonius.webp","Objeto_Arco_del_Sacrificio.webp","Objeto_Ultimo_Acorde.webp"]},
    {"nombre": "Rosaria",  "imagen": "Rosaria.jpg", "region": "Mondstadt", "rol": "Buffer", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["SueñosAureos.webp","EmblemadelDestino.webp","RitualDeLaNobleza.webp"], "equipos": [["HuTao.jpg","Rosaria.jpg","Xingchiu.jpg","Zhongli.jpg"],["Eula.jpg","Rosaria.jpg","Raiden.jpg","Zhongli.jpg"],["Chongyun.jpg","Rosaria.jpg","Kazuha.jpg","Bennett.jpg"]], "armas5": ["ArenasEscarlatas.webp","LunaCarmesi.webp","Homa.webp"], "armas4": ["LanzadelDuelo.webp","PerdiciondelDragon.webp","LaCaptura.webp"]},
    {"nombre": "Eula",  "imagen": "Eula.jpg", "region": "Mondstadt", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["LlamasAlbinas.webp","CaballeriaSanguinaria.webp","Gladiador.webp"], "equipos": [["Eula.jpg","Mika.jpg","Rosaria.jpg","Bennett.jpg"],["Eula.jpg","Raiden.jpg","Rosaria.jpg","Zhongli.jpg"],["Eula.jpg","Beidou.jpg","Chongyun.jpg","Zhongli.jpg"]], "armas5": ["OdadelosPinos.webp","LapidadelLobo.webp","MardeJuncos.webp"], "armas4": ["MeduladelaSerpiente.webp","ReydelosMares.webp","SombradelaMarea.webp"]},
    {"nombre": "Aloy",  "imagen": "Aloy.jpg", "region": "Mondstadt", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Derretidos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["NomadaDelInvierno.webp","RitualDeLaNobleza.webp","EmblemadelDestino.webp"], "equipos": [["Aloy.jpg","Xiangling.jpg","Kazuha.jpg","Diona.jpg"],["Aloy.jpg","Xiangling.jpg","Chongyun.jpg","Bennett.jpg"],["Aloy.jpg","Ayaka.jpg","Kokomi.jpg","Kazuha.jpg"]], "armas5": ["AgitadordelRelampago.webp","EstrellaInvernal.webp","AlasCelestiales.webp"], "armas4": ["Objeto_Ultimo_Acorde.webp","Objeto_Arco_del_Sacrificio.webp","PrototipoluzdeLuna.webp"]},
    {"nombre": "Mika",  "imagen": "Mika.jpg", "region": "Mondstadt", "rol": "Buffer", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["RitualDeLaNobleza.webp","PerlaOceanica.webp","SoñadordeAntaño.webp"], "equipos": [["Eula.jpg","Mika.jpg","Miko.jpg","Nahida.jpg"],["Eula.jpg","Mika.jpg","Rosaria.jpg","Bennett.jpg"],["Eula.jpg","Mika.jpg","Raiden.jpg","Bennett.jpg"]], "armas5": ["SinfonistadeAromas.webp","LuzdelSegador.webp","ArenasEscarlatas.webp"], "armas4": ["LanzadeFavonius.webp","PrototipoEstelar.webp","LaCaptura.webp"]},
    {"nombre": "Chongyun",  "imagen": "Chongyun.jpg", "region": "Liyue", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Congelados/Derretidos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["RitualDeLaNobleza.webp","EmblemadelDestino.webp","NomadaDelInvierno.webp"], "equipos": [["Ayaka.jpg","Chongyun.jpg","Xingchiu.jpg","Jean.jpg"],["Keching.jpg","Chongyun.jpg","Diona.jpg","Jean.jpg"],["Zhongli.jpg","Chongyun.jpg","Xiao.jpg","Jean.jpg"]], "armas5": ["LapidadelLobo.webp","OrgulloCelestial.webp","MardeJuncos.webp"], "armas4": ["GranEspadaSacrificio.webp","GranEspadadeFavonius.webp","PrototipoArcaico.webp"]},
    {"nombre": "Qiqi",  "imagen": "Qiqi.jpg", "region": "Liyue", "rol": "Healer", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["TenacidaddelaGeoarmada.webp","PergaminoHeroe.webp","PerlaOceanica.webp"], "equipos": [["Razor.jpg","Sacarosa.jpg","Zhongli.jpg","Qiqi.jpg"],["Eula.jpg","Raiden.jpg","Beidou.jpg","Qiqi.jpg"],["Fischl.jpg","Ninguang.jpg","Zhongli.jpg","Qiqi.jpg"]], "armas5": ["HimnodelasCumbres.webp","Objeto_Hoja_Afilada_Celestial.webp","ReflejodelasTinieblas.webp"], "armas4": ["EspadadelSacrificio.webp","Objeto_Espada_de_Favonius.webp","Tubo.webp"]},
    {"nombre": "Ganyu",  "imagen": "Ganyu.jpg", "region": "Liyue", "rol": "Main dps/Sub dps", "elemento": "Cryo", "reacciones": "Derretidos/Superconductor", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["OrquestaErrante.webp","Reminiscencia.webp","SueñosAureos.webp"], "equipos": [["Ayaka.jpg","Ganyu.jpg","Kazuha.jpg","Xingchiu.jpg"],["Mona.jpg","Ganyu.jpg","Diona.jpg","Venti.jpg"],["Mona.jpg","Ganyu.jpg","Diona.jpg","Kazuha.jpg"]], "armas5": ["NumerodeMagia.webp","EstrellaInvernal.webp","ArcodeAmos.webp"], "armas4": ["PrototipoluzdeLuna.webp","Objeto_Arco_del_Sacrificio.webp","Objeto_Ultimo_Acorde.webp"]},
    {"nombre": "Shenhe", "imagen": "Shenhe.jpg", "region": "Liyue", "rol": " Buffer/Suport", "elemento": "Cryo", "reacciones": "Congelados/Derretidos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["RitualDeLaNobleza.webp","PergaminoHeroe.webp","Gladiador.webp"], "equipos": [["Ayaka.jpg","Shenhe.jpg","Kazuha.jpg","Kokomi.jpg"],["Ganyu.jpg","Shenhe.jpg","Venti.jpg","Kokomi.jpg"],["Ganyu.jpg","Shenhe.jpg","Xiangling.jpg","Bennett.jpg"]], "armas5": ["PacificadoradelDesastre.webp","LuzdelSegador.webp","SinfonistadeAromas.webp"], "armas4": ["LanzadeFavonius.webp","CharlaPabellon.webp","PrototipoEstelar.webp"]},
    {"nombre": "Kamisato Ayaka", "imagen": "Ayaka.jpg", "region": "Inazuma", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Congelados/Superconductor", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Laila", "imagen": "Layla.jpg", "region": "Sumeru", "rol": "Escudo", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Fréminet", "imagen": "Freminet.jpg", "region": "Fontaine", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Wirothesley", "imagen": "Wirothesley.jpg", "region": "Fontaine", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Derretidos", "talentos": "Habilidad Elemental > Ataque Básico > Habilidad Definitiva", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Charlotte", "imagen": "Charlotte.jpg", "region": "Fontaine", "rol": "Healer", "elemento": "Cryo", "reacciones": "Congelados/Superconductor", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Escoffier", "imagen": "Escoffier.jpg", "region": "Fontaine", "rol": "Buffer/Healer", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Citlalí", "imagen": "Citlali.jpg", "Natlan": "text", "rol": "Buffer", "elemento": "Cryo", "reacciones": "Derretidos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Skirk", "imagen": "Skirk.jpg", "region": "Natlan", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Ataque Básico > Habilidad Definitiva > Habilidad Elemental", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Capitano", "imagen": "CapitanoF.jpg", "region": "Snezhnaya", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Derretidos/Congelados", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 1000 vida %, 160 Recarga de Energía, 200 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["RequiemDelCorredor.webp","CazadorFantasmal.webp","NomadaDelInvierno.webp"], "equipos": [["Shenhe.jpg","Xilonen.jpg","Mavuika.jpg","CapitanoF.jpg"],["Escoffier.jpg","Yelan.jpg","Skirk.jpg","CapitanoF.jpg"],["Nicole.jpg","Bennett.jpg","Durin.jpg","CapitanoF.jpg"]], "armas5": ["AlmaCongelada.jpg","FulgorCeruleo.webp","Expiadora.webp"], "armas4": ["Objeto_Colmillo_Lupino.webp","Objeto_Calamidad_de_Eshu.webp","Requiem_Abisal.webp"]},
]


def CryoView(page: ft.Page, user: dict, on_volver=None):
    from views.pyros import _ElementoView
    return _ElementoView(page, user, on_volver, "Cryo", "#93c5fd", PERSONAJES)
