import flet as ft
from views.PersonajeDetalle import PersonajeDetalle

PERSONAJES = [
    {"nombre": "Personaje 1",  "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 2",  "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 3",  "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 4",  "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 5",  "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 6",  "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 7",  "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 8",  "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 9",  "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 10", "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 11", "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 12", "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 13", "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 14", "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 15", "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 16", "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 17", "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Personaje 18", "imagen": "", "region": "text", "rol": "", "elemento": "Cryo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Capitano", "imagen": "CapitanoF.jpg", "region": "Snezhnaya", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Derretidos/Congelados", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 1000 vida %, 160 Recarga de Energía, 200 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["RequiemDelCorredor.webp","CazadorFantasmal.webp","NomadaDelInvierno.webp"], "equipos": [["Shenhe.jpg","Xilonen.jpg","Mavuika.jpg","CapitanoF.jpeg"],["Escoffier.jpg","Yelan.jpg","Skirk.jpg","CapitanoF.jpeg"],["Nicole.jpg","Bennett.jpg","Durin.jpg","CapitanoF.jpeg"]], "armas5": ["AlmaCongelada.jpg","FulgorCeruleo.webp","Expiadora.webp"], "armas4": ["Objeto_Colmillo_Lupino.webp","Objeto_Calamidad_de_Eshu.webp","Requiem_Abisal.webp"]},
]


def CryoView(page: ft.Page, user: dict, on_volver=None):
    from views.pyros import _ElementoView
    return _ElementoView(page, user, on_volver, "Cryo", "#93c5fd", PERSONAJES)
