import flet as ft
from views.PersonajeDetalle import PersonajeDetalle

PERSONAJES = [
    {"nombre": "Kaeya",  "imagen": "Kaeya.jpg", "region": "Mondstadt", "rol": "Sub dps", "elemento": "Cryo", "reacciones": "Congelados/Derretidos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["NomadaDelInvierno.webp","EmblemadelDestino.webp","RitualDeLaNobleza.webp"], "equipos": [["HuTao.jpg","Kaeya.jpg","Xingchiu.jpg","Zhongli.jpg"],["Chongyun.jpg","Kaeya.jpg","Xiangling.jpg","Bennett.jpg"],["Ayaka.jpg","Kaeya.jpg","Venti.jpg","Ayaka.jpg"]], "armas5": ["Objeto_Aquila_Favonia.webp","ReflejodelasTinieblas.webp","Objeto_Hoja_Afilada_Celestial.webp"], "armas4": ["Objeto_Espada_de_Favonius.webp","Requiem_Abisal.webp","EspinadeHierro.jpg"]},
    {"nombre": "Diona",  "imagen": "Diona.jpg", "region": "Mondstadt", "rol": "Escudo/Healer", "elemento": "Cryo", "reacciones": "Congelados/Superconductor", "talentos": "Habilidaad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Rosaria",  "imagen": "Rosaria.jpg", "region": "Mondstadt", "rol": "Buffer", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Eula",  "imagen": "Eula.jpg", "region": "Mondstadt", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Aloy",  "imagen": "Aloy.jpg", "region": "Mondstadt", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Derretidos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Mika",  "imagen": "Mika.jpg", "region": "Mondstadt", "rol": "Buffer", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Chongyun",  "imagen": "Chongyun.jpg", "region": "Liyue", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Congelados/Derretidos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Qiqi",  "imagen": "Qiqi.jpg", "region": "Liyue", "rol": "Healer", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Ganyu",  "imagen": "Ganyu.jpg", "region": "Liyue", "rol": "Main dps/Sub dps", "elemento": "Cryo", "reacciones": "Derretidos/Superconductor", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Shenhe", "imagen": "Shenhe.jpg", "region": "Liyue", "rol": " Buffer/Suport", "elemento": "Cryo", "reacciones": "Congelados/Derretidos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Kamisato Ayaka", "imagen": "Ayaka.jpg", "region": "Inazuma", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Congelados/Superconductor", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Laila", "imagen": "Layla.jpg", "region": "Sumeru", "rol": "Escudo", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Fréminet", "imagen": "Freminet.jpg", "region": "Fontaine", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Wirothesley", "imagen": "Wirothesley.jpg", "region": "Fontaine", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Derretidos", "talentos": "Habilidad Elemental > Ataque Básico > Habilidad Definitiva", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Charlotte", "imagen": "Charlotte.jpg", "region": "Fontaine", "rol": "Healer", "elemento": "Cryo", "reacciones": "Congelados/Superconductor", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Escoffier", "imagen": "Escoffier.jpg", "region": "Fontaine", "rol": "Buffer/Healer", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Citlalí", "imagen": "Citlali.jpg", "Natlan": "text", "rol": "Buffer", "elemento": "Cryo", "reacciones": "Derretidos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Skirk", "imagen": "Skirk.jpg", "region": "Natlan", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Congelados", "talentos": "Ataque Básico > Habilidad Definitiva > Habilidad Elemental", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Capitano", "imagen": "CapitanoF.jpg", "region": "Snezhnaya", "rol": "Main dps", "elemento": "Cryo", "reacciones": "Derretidos/Congelados", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 1000 vida %, 160 Recarga de Energía, 200 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["RequiemDelCorredor.webp","CazadorFantasmal.webp","NomadaDelInvierno.webp"], "equipos": [["Shenhe.jpg","Xilonen.jpg","Mavuika.jpg","CapitanoF.jpg"],["Escoffier.jpg","Yelan.jpg","Skirk.jpg","CapitanoF.jpg"],["Nicole.jpg","Bennett.jpg","Durin.jpg","CapitanoF.jpg"]], "armas5": ["AlmaCongelada.jpg","FulgorCeruleo.webp","Expiadora.webp"], "armas4": ["Objeto_Colmillo_Lupino.webp","Objeto_Calamidad_de_Eshu.webp","Requiem_Abisal.webp"]},
]


def CryoView(page: ft.Page, user: dict, on_volver=None):
    from views.pyros import _ElementoView
    return _ElementoView(page, user, on_volver, "Cryo", "#93c5fd", PERSONAJES)
