import flet as ft
from views.PersonajeDetalle import PersonajeDetalle

PERSONAJES = [
    {"nombre": "Yaoyao",  "imagen": "Yaoyao.jpg", "region": "Liyue", "rol": "Healer", "elemento": "Dendro", "reacciones": "Sobreflorecimiento", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "1500 ataque %, 1500 defensa %, 3000 vida %, 180 Recarga de Energía, 400 Maestría Elemental, 150 Daño crítico, 70% Probabilidad Crítica", "artefactos": ["RecuerdosdelBosque.webp","TenacidaddelaGeoarmada.webp","Instructor.webp"], "equipos": [["Alhacen.jpg","Xingchiu.jpg","Raiden.jpg","Yaoyao.jpg"],["Keching.jpg","Fischl.jpg","Kazuha.jpg","Yaoyao.jpg"],["Ayato.jpg","Nahida.jpg","Nilou.jpg","Yaoyao.jpg"]], "armas5": ["HaloFracturado.webp","Homa.webp","Halcon.webp"], "armas4": ["LanzadeFavonius.webp","CharlaPabellon.webp","LaCaptura.webp"]},
    {"nombre": "Baizhu",  "imagen": "Baizhu.jpg", "region": "Liyue", "rol": "Healer/Escudo", "elemento": "Dendro", "reacciones": "Sobreflorecimiento/Quemadura", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "1500 ataque %, 1500 defensa %, 1000 vida %, 180 Recarga de Energía, 800 Maestría Elemental, 170 Daño crítico, 70% Probabilidad Crítica", "artefactos": ["RecuerdosdelBosque.webp","PerlaOceanica.webp","Instructor.webp"], "equipos": [["Ayato.jpg","Nilou.jpg","Nahida.jpg","Baizhu.jpg"],["Kaveh.jpg","Xingchiu.jpg","Nilou.jpg","Baizhu.jpg"],["Alhacen.jpg","Miko.jpg","Nahida.jpg","Baizhu.jpg"]], "armas5": ["Jadefall.jpg","MilNoches.webp","Tejenoches.webp"], "armas4": ["PrototipoAmbar.webp","CodicedeFavonius.webp","Hakushin.webp"]},
    {"nombre": "Kirara",  "imagen": "Kirara.jpg", "region": "Inazuma", "rol": "Buffer", "elemento": "Dendro", "reacciones": "Sobreflorecimiento", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 1000 vida %, 180 Recarga de Energía, 800 Maestría Elemental, 170 Daño crítico, 70% Probabilidad Crítica", "artefactos": ["Instructor.webp","RecuerdosdelBosque.webp","RitualDeLaNobleza.webp"], "equipos": [["Ayato.jpg","Nahida.jpg","Shinobu.jpg","Kirara.jpg"],["Nahida.jpg","Barbara.jpg","Nilou.jpg","Kirara.jpg"],["Alhacen.jpg","Raiden.jpg","Nahida.jpg","Kirara.jpg"]], "armas5": ["JuramentoporlaLibertad.webp","Objeto_Hoja_Afilada_Celestial.webp","Objeto_Aquila_Favonia.webp"], "armas4": ["Objeto_Espada_de_Favonius.webp","EspadadelSacrificio.webp","Albura.jpg"]},
    {"nombre": "Tignari",  "imagen": "Tignari.jpg", "region": "Sumeru", "rol": "Main dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento/Quemadura", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "1500 ataque %, 1500 defensa %, 1000 vida %, 170 Recarga de Energía, 800 Maestría Elemental, 200 Daño crítico, 90% Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Collei",  "imagen": "Collei.jpg", "region": "Sumeru", "rol": "Sub dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento/Quemadura", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "1500 ataque %, 1500 defensa %, 1000 vida %, 160 Recarga de Energía, 800 Maestría Elemental, 170 Daño crítico, 70% Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Nahida",  "imagen": "Nahida.jpg", "region": "Sumeru", "rol": "Buffer/Sub dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento/Quemadura", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "1500 ataque %, 1500 defensa %, 1000 vida %, 180 Recarga de Energía, 1000 Maestría Elemental, 170 Daño crítico, 70% Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Alhacén",  "imagen": "Alhacen.jpg", "region": "Sumeru", "rol": "Main dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento/Quemadura", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "1500 ataque %, 1500 defensa %, 1000 vida %, 170 Recarga de Energía, 800 Maestría Elemental, 200 Daño crítico, 90% Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Kaveh",  "imagen": "Kaveh.jpg", "region": "Sumeru", "rol": "Main dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento", "talentos": "Habilidad Elemental > Ataque Básico > Habilidad Definitiva", "estadisticas": "1500 ataque %, 1500 defensa %, 1000 vida %, 170 Recarga de Energía, 800 Maestría Elemental, 200 Daño crítico, 90% Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Émilie",  "imagen": "Emilie.jpg", "region": "Fontaine", "rol": "Suport/Sub dps", "elemento": "Dendro", "reacciones": "Quemadura", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "1500 ataque %, 1500 defensa %, 1000 vida %, 180 Recarga de Energía, 800 Maestría Elemental, 200 Daño crítico, 90% Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Kinich", "imagen": "Kinich.jpg", "region": "Natlan", "rol": "Main dps", "elemento": "Dendro", "reacciones": "Quemadura", "talentos": "Habilidad Elemental > Ataque Básico > Habilidad Definitiva", "estadisticas": "1500 ataque %, 1500 defensa %, 1000 vida %, 170 Recarga de Energía, 800 Maestría Elemental, 200 Daño crítico, 90% Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Lauma", "imagen": "Lauma.jpg", "region": "Nod Krai", "rol": "Suport/Sub dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento Lunar", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "1500 ataque %, 1500 defensa %, 2000 vida %, 180 Recarga de Energía, 800 Maestría Elemental, 200 Daño crítico, 90% Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Nefer", "imagen": "Nefer.jpg", "region": "Nod Krai", "rol": "Main dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento Lunar", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico",'estadisticas': '1500 ataque %, 1500 defensa %, 1000 vida %, 170 Recarga de Energía, 800 Maestría Elemental, 200 Daño crítico, 90% Probabilidad Crítica', 'artefactos': ['','',''], 'equipos': [['','','',''],['','','',''],['','','','']], 'armas5': ['','',''], 'armas4': ['','','']},
]


def DendroView(page: ft.Page, user: dict, on_volver=None):
    from views.pyros import _ElementoView
    return _ElementoView(page, user, on_volver, "Dendro", "#4ade80", PERSONAJES)
