import flet as ft
from views.PersonajeDetalle import PersonajeDetalle

PERSONAJES = [
    {"nombre": "Yaoyao",  "imagen": "Yaoyao.jpg", "region": "Liyue", "rol": "Healer", "elemento": "Dendro", "reacciones": "Sobreflorecimiento", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 1000 vida %, 160 Recarga de Energía, 200 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["RecuerdosdelBosque.webp","TenacidaddelaGeoarmada.webp","Instructor.webp"], "equipos": [["Alhacen.jpg","Xingchiu.jpg","Raiden.jpg","Yaoyao.jpg"],["Keching.jpg","Fischl.jpg","Kazuha.jpg","Yaoyao.jpg"],["Ayato.jpg","Nahida.jpg","Nilou.jpg","Yaoyao.jpg"]], "armas5": ["HaloFracturado.webp","Homa.webp","Halcon.webp"], "armas4": ["LanzadeFavonius.webp","CharlaPabellon.webp","LaCaptura.webp"]},
    {"nombre": "Baizhu",  "imagen": "Baizhu.jpg", "region": "Liyue", "rol": "Healer/Escudo", "elemento": "Dendro", "reacciones": "Sobreflorecimiento/Quemadura", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Kirara",  "imagen": "Kirara.jpg", "region": "Inazuma", "rol": "Buffer", "elemento": "Dendro", "reacciones": "Sobreflorecimiento", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Tignari",  "imagen": "Tignari.jpg", "region": "Sumeru", "rol": "Main dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento/Quemadura", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Collei",  "imagen": "Collei.jpg", "region": "Sumeru", "rol": "Sub dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento/Quemadura", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Nahida",  "imagen": "Nahida.jpg", "region": "Sumeru", "rol": "Buffer/Sub dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento/Quemadura", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Alhacén",  "imagen": "Alhacen.jpg", "region": "Sumeru", "rol": "Main dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento/Quemadura", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Kaveh",  "imagen": "Kaveh.jpg", "region": "Sumeru", "rol": "Main dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento", "talentos": "Habilidad Elemental > Ataque Básico > Habilidad Definitiva", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Émilie",  "imagen": "Emilie.jpg", "region": "Fontaine", "rol": "Suport/Sub dps", "elemento": "Dendro", "reacciones": "Quemadura", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Kinich", "imagen": "Kinich.jpg", "region": "Natlan", "rol": "Main dps", "elemento": "Dendro", "reacciones": "Quemadura", "talentos": "Habilidad Elemental > Ataque Básico > Habilidad Definitiva", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Lauma", "imagen": "Lauma.jpg", "region": "Nod Krai", "rol": "Suport/Sub dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento Lunar", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Nefer", "imagen": "Nefer.jpg", "region": "Nod Krai", "rol": "Main dps", "elemento": "Dendro", "reacciones": "Sobreflorecimiento Lunar", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico",'estadisticas': 'text', 'artefactos': ['','',''], 'equipos': [['','','',''],['','','',''],['','','','']], 'armas5': ['','',''], 'armas4': ['','','']},
]


def DendroView(page: ft.Page, user: dict, on_volver=None):
    from views.pyros import _ElementoView
    return _ElementoView(page, user, on_volver, "Dendro", "#4ade80", PERSONAJES)
