import flet as ft
from views.PersonajeDetalle import PersonajeDetalle

PERSONAJES = [
    {"nombre": "Lisa",  "imagen": "lisa.jpg", "region": "Mondstadt", "rol": "Sub dps", "elemento": "Electro", "reacciones": "Sobrecarga", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 1000 vida %, 160 Recarga de Energía, 200 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["FuriadelTrueno.webp","SueñosAureos.jpg","OrquestaErrante.webp"], "equipos": [["Raiden.jpg","Sara.jpg","lisa.jpg","Bennett.jpg"],["Eula.jpg","lisa.jpg","Rosaria.jpg","Zhongli.jpg"],["Diluc.jpg","lisa.jpg","Kazuha.jpg","Bennett.jpg"]], "armas5": ["AxiomadelaKagura.webp","MilNoches.webp","OracionPerdida.webp"], "armas4": ["SinfoniadelosMerodeadores.webp","PerlaSolar.webp","FluenciaImpoluta.webp"]},
    {"nombre": "Razor",  "imagen": "Razor.jpg", "region": "Mondstadt", "rol": "Main dps", "elemento": "Electro", "reacciones": "Sobrecarga", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 1000 vida %, 180 Recarga de Energía, 300 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["DiadelosVientos.webp","EmblemadelDestino.webp","FuriadelTrueno.webp"], "equipos": [["Razor.jpg","Durin.jpg","Bennett.jpg","Chevreuse.jpg"],["Razor.jpg","Durin.jpg","Bennett.jpg","Fischl.jpg"],["Razor.jpg","Fischl.jpg","Albedo.jpg","Bennett.jpg"]], "armas5": ["CantardelLobo.webp","MilSolesAbrasadores.webp","MardeJuncos.webp"], "armas4": ["MeduladelaSerpiente.webp","SombradelaMarea.webp","GranEspadaSacrificio.webp"]},
    {"nombre": "Fischl",  "imagen": "Fischl.jpg", "region": "Mondstadt", "rol": "Sub dps", "elemento": "Electro", "reacciones": "Sobrecarga/Electrocarga", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 1000 vida %, 160 Recarga de Energía, 200 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["CompañiaDorada.webp","DiadelosVientos.webp","FuriadelTrueno.webp"], "equipos": [["Clorinde.jpg","Fischl.jpg","Mavuika.jpg","Chevreuse.jpg"],["Chasca.jpg","Fischl.jpg","Furina.jpg","Bennett.jpg"],["Arle.jpg","Fischl.jpg","Chevreuse.jpg","Bennett.jpg"]], "armas5": ["EstrellaInvernal.webp","SendaCazadora.webp","AquaSimulacra.webp"], "armas4": ["Objeto_Arco_de_Favonius.webp","Objeto_Arco_del_Sacrificio.webp","Objeto_Ultimo_Acorde.webp"]},
    {"nombre": "Beidou",  "imagen": "Beidou.jpg", "region": "Liyue", "rol": "Escudo", "elemento": "Electro", "reacciones": "Sobrecargados/Electrocargados", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Keching",  "imagen": "Keching.jpg", "region": "Liyue", "rol": "Main dps", "elemento": "Electro", "reacciones": "Sobrecargados/Electrocargados", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Shogun Raiden",  "imagen": "Raiden.jpg", "region": "Inazuma", "rol": "Sub dps", "elemento": "Electro", "reacciones": "Electrocargados/Sobreflorecimiento", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Kujou Sara",  "imagen": "Sara.jpg", "region": "Inazuma", "rol": "Buffer", "elemento": "Electro", "reacciones": "Electrocargados", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Yae Miko",  "imagen": "Miko.jpg", "region": "Inazuma", "rol": "Sub dps", "elemento": "Electro", "reacciones": "Electrocargados/Sobrecargados", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Kuki Shinobu",  "imagen": "Shinobu.jpg", "region": "Inazuma", "rol": "Sub dps/Healer", "elemento": "Electro", "reacciones": "Electrocargados/Sobrecargados", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Dori", "imagen": "Dori.jpg", "region": "Sumeru", "rol": "Main dps", "elemento": "Electro", "reacciones": "Sobreflorecimiento", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Cyno", "imagen": "Cyno.jpg", "region": "Sumeru", "rol": "Main dps", "elemento": "Electro", "reacciones": "Sobrecargados", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Sethos", "imagen": "Sethos.jpg", "region": "Sumeru", "rol": "Main dps", "elemento": "Electro", "reacciones": "Sobrecargados", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Clorinde", "imagen": "Clorinde.jpg", "region": "Clorinde", "rol": "Main dps", "elemento": "Electro", "reacciones": "Sobrecargados", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Ororon", "imagen": "Ororon.jpg", "region": "Natlan", "rol": "Sub dps", "elemento": "Electro", "reacciones": "Sobrecargados/Electrocargados", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Varesa", "imagen": "Varesa.jpg", "region": "Natlan", "rol": "Main dps", "elemento": "Electro", "reacciones": "Sobrecargados", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Iansán", "imagen": "Iansan.jpg", "region": "Natlan", "rol": "Buffer", "elemento": "Electro", "reacciones": "Sobrecargados", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Ineffa", "imagen": "Ineffa.jpg", "region": "Nod Krai", "rol": "Sub dps/Buffer", "elemento": "Electro", "reacciones": "Electrocargado/Sobreflorecimiento Lunar", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Flins", "imagen": "Flins.jpg", "region": "Nod Krai", "rol": "Main dps", "elemento": "Electro", "reacciones": "Electrocargado Lunar/Sobreflorecimiento Lunar", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
]


def ElectroView(page: ft.Page, user: dict, on_volver=None):
    from views.pyros import _ElementoView
    return _ElementoView(page, user, on_volver, "Electro", "#c084fc", PERSONAJES)
