import flet as ft
from views.PersonajeDetalle import PersonajeDetalle

PERSONAJES = [
    {"nombre": "Noelle",  "imagen": "Noelle.jpg", "region": "Mondstadt", "rol": "Main dps/Escudo", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 3000 defensa %, 1000 vida %, 170 Recarga de Energía, 50 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["CazadorFantasmal.webp","Gladiador.webp","TenacidaddelaGeoarmada.webp"], "equipos": [["Itto.jpg","Noelle.jpg","Gorou.jpg","Zhongli.jpg"],["Xiao.jpg","Jean.jpg","Noelle.jpg","Zhongli.jpg"],["Noelle.jpg","Albedo.jpg","Gorou.jpg","Zhongli.jpg"]], "armas5": ["OrgulloCelestial.webp","ColmillodelRey.webp","MilSolesAbrasadores.webp"], "armas4": ["MeduladelaSerpiente.webp","GranEspadadeFavonius.webp","PrototipoArcaico.webp"]},
    {"nombre": "Albedo",  "imagen": "Albedo.jpg", "region": "Monstadt", "rol": "Sub dps", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 3000 defensa %, 1000 vida %, 170 Recarga de Energía, 50 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["Cascara.webp","Petra.webp","CompañiaDorada.webp"], "equipos": [["Venti.jpg","Faruzan.jpg","Bennett.jpg","Albedo.jpg"],["Klee.jpg","Durin.jpg","Bennett.jpg","Albedo.jpg"],["Mizuki.jpg","Durin.jpg","Venti.jpg","Albedo.jpg"]], "armas5": ["HimnodelasCumbres.webp","Cortatelones.webp","Clorofilo.webp"], "armas4": ["Objeto_Espada_de_Favonius.webp","DeseoPonsoñoso.webp","Amenoma.webp"]},
    {"nombre": "Ninguang",  "imagen": "Ningguang.jpg", "region": "Liyue", "rol": "Suport/Sub dps", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 3000 defensa %, 1000 vida %, 170 Recarga de Energía, 50 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["Petra.webp","RitualDeLaNobleza.webp","Gladiador.webp"], "equipos": [["Xiao.jpg","Jean.jpg","Zhongli.jpg","Ningguang.jpg"],["HuTao.jpg","Xingchiu.jpg","Zhongli.jpg","Ningguang.jpg"],["Beidou.jpg","Fischl.jpg","Jean.jpg","Ningguang.jpg"]], "armas5": ["AxiomadelaKagura.webp","OracionPerdida.webp","Supervision.webp"], "armas4": ["MemoriasdeSacrificios.webp","PerlaSolar.webp","CartaNautica.webp"]},
    {"nombre": "Zhongli",  "imagen": "Zhongli.jpg", "region": "Liyue", "rol": "Escudo", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1000 defensa %, 3000 vida %, 180 Recarga de Energía, 50 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["Petra.webp","PergaminoHeroe.webp","RecuerdosdelBosque.webp"], "equipos": [["Keching.jpg","Fischl.jpg","Nahida.jpg","Zhongli.jpg"],["Xiao.jpg","Jean.jpg","Albedo.jpg","Zhongli.jpg"],["HuTao.jpg","Xingchiu.jpg","Kazuha.jpg","Zhongli.jpg"]], "armas5": ["Homa.webp","Lumidulce.webp","Halcon.webp"], "armas4": ["LaCaptura.webp","LanzadelDuelo.webp","LanzadeFavonius.webp"]},
    {"nombre": "Yun Jin",  "imagen": "Yunjin.jpg", "region": "Liyue", "rol": "Buffer", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "1000 ataque %, 3000 defensa %, 2000 vida %, 190 Recarga de Energía, 50 Maestría Elemental, 160 Daño crítico %, 60 Probabilidad Crítica", "artefactos": ["Cascara.webp","EmblemadelDestino.webp","RitualDeLaNobleza.webp"], "equipos": [["Yoimiya.jpg","Yunjin.jpg","Xingchiu.jpg","Bennett.jpg"],["Ayato.jpg","Yunjin.jpg","HuTao.jpg","Zhongli.jpg"],["Ayato.jpg","Yunjin.jpg","Yoimiya.jpg","Zhongli.jpg"]], "armas5": ["LuzdelSegador.webp","Homa.webp","ArenasEscarlatas.webp"], "armas4": ["LanzadeFavonius.webp","LaCaptura.webp","Kitai.webp"]},
    {"nombre": "Zibai",  "imagen": "Zibai.jpg", "region": "Liyue", "rol": "Main dps", "elemento": "Geo", "reacciones": "Cristalizado Lunar", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 1000 defensa %, 1000 vida %, 200 Recarga de Energía, 800 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["FlinsFlor.webp","Cascara.webp","OrquestaErrante.webp"], "equipos": [["Zibai.jpg","Illuga.jpg","Colombina.jpg","Linnea.jpg"],["Zibai.jpg","Illuga.jpg","Colombina.jpg","Zhongli.jpg"],["Zibai.jpg","Linnea.jpg","Colombina.jpg","Xilonen.jpg"]], "armas5": ["Refulgencia.webp","Cortatelones.webp","Clorofilo.webp"], "armas4": ["DeseoPonsoñoso.webp","Amenoma.webp","Objeto_Espada_de_Favonius.webp"]},
    {"nombre": "Arataki Itto",  "imagen": "Itto.jpg", "region": "Inazuma", "rol": "Main dps", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Ataque Básico > Habilidad Definitiva > Habilidad Elemental", "estadisticas": "2000 ataque %, 3000 defensa %, 1000 vida %, 190 Recarga de Energía, 50 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["Cascara.webp","Pabellon.webp","Petra.webp"], "equipos": [["Itto.jpg","Albedo.jpg","Gorou.jpg","Zhongli.jpg"],["Itto.jpg","Noelle.jpg","Gorou.jpg","Zhongli.jpg"],["Itto.jpg","Chiori.jpg","Zhongli.jpg","Gorou.jpg"]], "armas5": ["Cornirrojo.webp","MardeJuncos.webp","Veredicto.webp"], "armas4": ["MeduladelaSerpiente.webp","Whiteblind.webp","GranEspadadeFavonius.webp"]},
    {"nombre": "Gorou",  "imagen": "Gorou.jpg", "region": "Inazuma", "rol": "Buffer", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "1000 ataque %, 3000 defensa %, 1000 vida %, 200 Recarga de Energía, 50 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["RitualDeLaNobleza.webp","PergaminoHeroe.webp","EmblemadelDestino.webp"], "equipos": [["Itto.jpg","Noelle.jpg","Gorou.jpg","Zhongli.jpg"],["Itto.jpg","Albedo.jpg","Gorou.jpg","Jean.jpg"],["Itto.jpg","Linnea.jpg","Gorou.jpg","Colombina.jpg"]], "armas5": ["ElegiadelFin.webp","EstrellaInvernal.webp","AlasCelestiales.webp"], "armas4": ["Objeto_Arco_de_Favonius.webp","GanchoTrampero.webp","Objeto_Arco_del_Sacrificio.webp"]},
    {"nombre": "Navia",  "imagen": "Navia.jpg", "region": "Fontaine", "rol": "Main dps", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1000 defensa %, 1000 vida %, 190 Recarga de Energía, 50 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["Murmullo.webp","CompañiaDorada.webp","CazadorFantasmal.webp"], "equipos": [["Navia.jpg","Zhongli.jpg","Xiangling.jpg","Bennett.jpg"],["Navia.jpg","Furina.jpg","Zhongli.jpg","Bennett.jpg"],["Navia.jpg","Xilonen.jpg","Mavuika.jpg","Bennett.jpg"]], "armas5": ["Veredicto.webp","MilSolesAbrasadores.webp","MardeJuncos.webp"], "armas4": ["MeduladelaSerpiente.webp","SombradelaMarea.webp","Terremoto.webp"]},
    {"nombre": "Chiori", "imagen": "Chiori.jpg", "region": "Fontaine", "rol": "Sub dps", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 3000 defensa %, 1000 vida %, 180 Recarga de Energía, 50 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["CompañiaDorada.webp","Cascara.webp","Petra.webp"], "equipos": [["Yoimiya.jpg","Yelan.jpg","Chiori.jpg","Zhongli.jpg"],["Navia.jpg","Furina.jpg","Chiori.jpg","Bennett.jpg"],["Zibai.jpg","Colombina.jpg","Chiori.jpg","Linnea.jpg"]], "armas5": ["Cortatelones.webp","Refulgencia.webp","Objeto_Cortador_de_Jade_Primordial.webp"], "armas4": ["Objeto_Colmillo_Lupino.webp","Objeto_Calamidad_de_Eshu.webp","Requiem_Abisal.webp"]},
    {"nombre": "Kachina", "imagen": "Kachina.jpg", "region": "Natlan", "rol": "Suport", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 3500 defensa %, 1000 vida %, 190 Recarga de Energía, 50 Maestría Elemental, 180 Daño crítico %, 80 Probabilidad Crítica", "artefactos": ["Petra.webp","RitualDeLaNobleza.webp","PergaminoHeroe.webp"], "equipos": [["Mualani.jpg","Kachina.jpg","Xiangling.jpg","Zhongli.jpg"],["Navia.jpg","Kachina.jpg","Xiangling.jpg","Bennett.jpg"],["Arle.jpg","Kachina.jpg","Kazuha.jpg","Bennett.jpg"]], "armas5": ["LuzdelSegador.webp","Homa.webp","ArenasEscarlatas.webp"], "armas4": ["LanzadeFavonius.webp","Arcoiris.webp","PrototipoEstelar.webp"]},
    {"nombre": "Xilonen", "imagen": "Xilonen.jpg", "region": "Natlan", "rol": "Suport/Healer", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 3500 defensa %, 1000 vida %, 200 Recarga de Energía, 50 Maestría Elemental, 180 Daño crítico %, 80 Probabilidad Crítica", "artefactos": ["PergaminoHeroe.webp","Petra.webp","RitualDeLaNobleza.webp"], "equipos": [["Xilonen.jpg","Gorou.jpg","Furina.jpg","Xianyun.jpg"],["Xilonen.jpg","Mualani.jpg","Xiangling.jpg","Zhongli.jpg"],["Xilonen.jpg","Chasca.jpg","Citlali.jpg","Bennett.jpg"]], "armas5": ["HimnodelasCumbres.webp","JuramentoporlaLibertad.webp","Refulgencia.webp"], "armas4": ["Objeto_Espada_de_Favonius.webp","Amenoma.webp","Requiem_Abisal.webp"]},
    {"nombre": "Illuga", "imagen": "Illuga.jpg", "region": "Nod Krai", "rol": "Suport", "elemento": "Geo", "reacciones": "Cristalizado Lunar", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1000 defensa %, 1000 vida %, 200 Recarga de Energía, 800 Maestría Elemental, 190 Daño crítico %, 80 Probabilidad Crítica", "artefactos": ["Serenata.webp","OrquestaErrante.webp","Petra.webp"], "equipos": [["Zibai.jpg","Illuga.jpg","Colombina.jpg","Gorou.jpg"],["Zibai.jpg","Illuga.jpg","Colombina.jpg","Zhongli.jpg"],["","Illuga.jpg","Colombina.jpg","Itto.jpg"]], "armas5": ["LuzdelSegador.webp","Homa.webp","Halcon.webp"], "armas4": ["LanzadeFavonius.webp","PerdiciondelDragon.webp","Kitai.webp"]},
    {"nombre": "Linnéa", "imagen": "Linnea.jpg", "region": "Nod Krai", "rol": "Sub dps/Healer", "elemento": "Geo", "reacciones": "Cristalizado Lunar", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1000 defensa %, 1000 vida %, 180 Recarga de Energía, 400 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["Alborada.webp","Cascara.webp","Serenata.webp"], "equipos": [["Linnea.jpg","Colombina.jpg","Zibai.jpg","Illuga.jpg"],["Linnea.jpg","Colombina.jpg","Navia.jpg","Furina.jpg"],["Linnea.jpg","Colombina.jpg","Itto.jpg","Gorou.jpg"]], "armas5": ["Escarchado.webp","AquaSimulacra.webp","EstrellaInvernal.webp"], "armas4": ["Objeto_Arco_de_Favonius.webp","Objeto_Ultimo_Acorde.webp","SolAbrasador.webp"]},
]


def GeoView(page: ft.Page, user: dict, on_volver=None):
    from views.pyros import _ElementoView
    return _ElementoView(page, user, on_volver, "Geo", "#fbbf24", PERSONAJES)
