import flet as ft
from views.PersonajeDetalle import PersonajeDetalle

PERSONAJES = [
    {"nombre": "Noelle",  "imagen": "Noelle.jpg", "region": "Mondstadt", "rol": "Escudo", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 1000 vida %, 160 Recarga de Energía, 200 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["CazadorFantasmal.webp","Gladiador.webp","TenacidaddelaGeoarmada.webp"], "equipos": [["Itto.jpg","Noelle.jpg","Gorou.jpg","Zhongli.jpg"],["Xiao.jpg","Jean.jpg","Noelle.jpg","Zhongli.jpg"],["Noelle.jpg","Albedo.jpg","Gorou.jpg","Zhongli.jpg"]], "armas5": ["OrgulloCelestial.webp","ColmillodelRey.webp","MilSolesAbrasadores.webp"], "armas4": ["MeduladelaSerpiente.jpg","GranEspadadeFavonius.webp","PrototipoArcaico.webp"]},
    {"nombre": "Albedo",  "imagen": "Albedo.jpg", "region": "text", "rol": "", "elemento": "Geo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Ninguang",  "imagen": "Ninguang.jpg", "region": "text", "rol": "", "elemento": "Geo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Zhongli",  "imagen": "Zhongli.jpg", "region": "text", "rol": "", "elemento": "Geo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Yun Jin",  "imagen": "Yunjin.jpg", "region": "text", "rol": "", "elemento": "Geo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Zibai",  "imagen": "Zibai.jpg", "region": "text", "rol": "", "elemento": "Geo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Arataki Itto",  "imagen": "Itto.jpg", "region": "text", "rol": "", "elemento": "Geo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Gorou",  "imagen": "Gorou.jpg", "region": "text", "rol": "", "elemento": "Geo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Navia",  "imagen": "Navia.jpg", "region": "text", "rol": "", "elemento": "Geo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Chiori", "imagen": "Chiori.jpg", "region": "text", "rol": "", "elemento": "Geo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Kachina", "imagen": "Kachina.jpg", "region": "text", "rol": "", "elemento": "Geo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Xilonen", "imagen": "Xilonen.jpg", "region": "text", "rol": "", "elemento": "Geo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Illuga", "imagen": "Illuga.jpg", "region": "text", "rol": "", "elemento": "Geo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Linnéa", "imagen": "Linnea.jpg", "region": "text", "rol": "", "elemento": "Geo", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
]


def GeoView(page: ft.Page, user: dict, on_volver=None):
    from views.pyros import _ElementoView
    return _ElementoView(page, user, on_volver, "Geo", "#fbbf24", PERSONAJES)
