import flet as ft
from views.PersonajeDetalle import PersonajeDetalle

PERSONAJES = [
    {"nombre": "Noelle",  "imagen": "Noelle.jpg", "region": "Mondstadt", "rol": "Main dps/Escudo", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 3000 defensa %, 1000 vida %, 170 Recarga de Energía, 50 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["CazadorFantasmal.webp","Gladiador.webp","TenacidaddelaGeoarmada.webp"], "equipos": [["Itto.jpg","Noelle.jpg","Gorou.jpg","Zhongli.jpg"],["Xiao.jpg","Jean.jpg","Noelle.jpg","Zhongli.jpg"],["Noelle.jpg","Albedo.jpg","Gorou.jpg","Zhongli.jpg"]], "armas5": ["OrgulloCelestial.webp","ColmillodelRey.webp","MilSolesAbrasadores.webp"], "armas4": ["MeduladelaSerpiente.webp","GranEspadadeFavonius.webp","PrototipoArcaico.webp"]},
    {"nombre": "Albedo",  "imagen": "Albedo.jpg", "region": "Monstadt", "rol": "Sub dps", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 3000 defensa %, 1000 vida %, 170 Recarga de Energía, 50 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["Cascara.webp","Petra.webp","CompañiaDorada.webp"], "equipos": [["Venti.jpg","Faruzan.jpg","Bennett.jpg","Albedo.jpg"],["Klee.jpg","Durin.jpg","Bennett.jpg","Albedo.jpg"],["Mizuki.jpg","Durin.jpg","Venti.jpg","Albedo.jpg"]], "armas5": ["HimnodelasCumbres.webp","Cortatelones.webp","Clorofilo.webp"], "armas4": ["Objeto_Espada_de_Favonius.webp","DeseoPonsoñoso.webp","Amenoma.webp"]},
    {"nombre": "Ninguang",  "imagen": "Ningguang.jpg", "region": "Liyue", "rol": "Suport/Sub dps", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 3000 defensa %, 1000 vida %, 170 Recarga de Energía, 50 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["Petra.webp","RitualDeLaNobleza.webp","Gladiador.webp"], "equipos": [["Xiao.jpg","Jean.jpg","Zhongli.jpg","Ningguang.jpg"],["HuTao.jpg","Xingchiu.jpg","Zhongli.jpg","Ningguang.jpg"],["Beidou.jpg","Fischl.jpg","Jean.jpg","Ningguang.jpg"]], "armas5": ["AxiomadelaKagura.webp","OracionPerdida.webp","Supervision.webp"], "armas4": ["MemoriasdeSacrificios.webp","PerlaSolar.webp","CartaNautica.webp"]},
    {"nombre": "Zhongli",  "imagen": "Zhongli.jpg", "region": "Liyue", "rol": "Escudo", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1000 defensa %, 3000 vida %, 180 Recarga de Energía, 50 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Yun Jin",  "imagen": "Yunjin.jpg", "region": "Liyue", "rol": "Buffer", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "1000 ataque %, 3000 defensa %, 2000 vida %, 190 Recarga de Energía, 50 Maestría Elemental, 160 Daño crítico %, 60 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Zibai",  "imagen": "Zibai.jpg", "region": "Liyue", "rol": "Main dps", "elemento": "Geo", "reacciones": "Cristalizado Lunar", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 1000 defensa %, 1000 vida %, 200 Recarga de Energía, 800 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Arataki Itto",  "imagen": "Itto.jpg", "region": "Inazuma", "rol": "Main dps", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Ataque Básico > Habilidad Definitiva > Habilidad Elemental", "estadisticas": "2000 ataque %, 3000 defensa %, 1000 vida %, 190 Recarga de Energía, 50 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Gorou",  "imagen": "Gorou.jpg", "region": "Inazuma", "rol": "Buffer", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "1000 ataque %, 3000 defensa %, 1000 vida %, 200 Recarga de Energía, 50 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Navia",  "imagen": "Navia.jpg", "region": "Fontaine", "rol": "Main dps", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1000 defensa %, 1000 vida %, 190 Recarga de Energía, 50 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Chiori", "imagen": "Chiori.jpg", "region": "Fontaine", "rol": "Sub dps", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 3000 defensa %, 1000 vida %, 180 Recarga de Energía, 50 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Kachina", "imagen": "Kachina.jpg", "region": "Natlan", "rol": "Suport", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 3500 defensa %, 1000 vida %, 190 Recarga de Energía, 50 Maestría Elemental, 180 Daño crítico %, 80 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Xilonen", "imagen": "Xilonen.jpg", "region": "Natlan", "rol": "Suport/Healer", "elemento": "Geo", "reacciones": "Cristalizado", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 3500 defensa %, 1000 vida %, 200 Recarga de Energía, 50 Maestría Elemental, 180 Daño crítico %, 80 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Illuga", "imagen": "Illuga.jpg", "region": "Nod Krai", "rol": "Suport", "elemento": "Geo", "reacciones": "Cristalizado Lunar", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1000 defensa %, 1000 vida %, 200 Recarga de Energía, 800 Maestría Elemental, 190 Daño crítico %, 80 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Linnéa", "imagen": "Linnea.jpg", "region": "Nod Krai", "rol": "Sub dps/Healer", "elemento": "Geo", "reacciones": "Cristalizado Lunar", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1000 defensa %, 1000 vida %, 180 Recarga de Energía, 400 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
]


def GeoView(page: ft.Page, user: dict, on_volver=None):
    from views.pyros import _ElementoView
    return _ElementoView(page, user, on_volver, "Geo", "#fbbf24", PERSONAJES)
