import flet as ft
from views.PersonajeDetalle import PersonajeDetalle

PERSONAJES = [ 
    {"nombre": "Barbara",  "imagen": "Barbara.jpg", "region": "Mondstadt", "rol": "Healer", "elemento": "Hydro", "reacciones": "Congelados/Derretidos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "1200 ataque %, 1500 defensa %, 5000 vida %, 160 Recarga de Energía, 400 Maestría Elemental, 150 Daño crítico %, 70 Probabilidad Crítica", "artefactos": ["PerlaOceanica.webp","PergaminoHeroe.webp","Instructor.webp"], "equipos": [["HuTao.jpg","Xiangling.jpg","Barbara.jpg","Venti.jpg"],["Klee.jpg","Xiangling.jpg","Barbara.jpg","Sacarosa.jpg"],["Razor.jpg","Beidou.jpg","Barbara.jpg","Sacarosa.jpg"]], "armas5": ["VigiadelasEstrellas.webp","MilNoches.webp","Hibernacion.webp"], "armas4": ["MemoriasdeSacrificios.webp","Laud.webp","CartaNautica.webp"]},
    {"nombre": "Mona",  "imagen": "Mona.jpg", "region": "Mondstadt", "rol": "Buffer/Sub dps", "elemento": "Hydro", "reacciones": "Congelados/Electrocargados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 1000 vida %, 160 Recarga de Energía, 300 Maestría Elemental, 180 Daño crítico %, 70 Probabilidad Crítica", "artefactos": ["CorazonProfundidades.webp","RitualDeLaNobleza.webp","Gladiador.webp"], "equipos": [["Mona.jpg","Xingchiu.jpg","Jahoda.jpg","Ineffa.jpg"],["Mona.jpg","Furina.jpg","Jahoda.jpg","Ineffa.jpg"],["Mona.jpg","Fischl.jpg","Sacarosa.jpg","Ineffa.jpg"]], "armas5": ["OracionPerdida.webp","PergaminoCelestial.webp","MilNoches.webp"], "armas4": ["SinfoniadelosMerodeadores.webp","PerlaSolar.webp","CartaNautica.webp"]},
    {"nombre": "Dalhia",  "imagen": "Dahlia.jpg", "region": "Mondstadt", "rol": "Suport", "elemento": "Hydro", "reacciones": "Congelados/Vaporizados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 5000 vida %, 170 Recarga de Energía, 300 Maestría Elemental, 180 Daño crítico %, 70 Probabilidad Crítica", "artefactos": ["RitualDeLaNobleza.webp","PergaminoHeroe.webp","Petra.webp"], "equipos": [["Skirk.jpg","Furina.jpg","Dahlia.jpg","CapitanoF.jpg"],["Trotamundos.jpg","Faruzan.jpg","Dahlia.jpg","Bennett.jpg"],["Yoimiya.jpg","Yelan.jpg","Dahlia.jpg","Bennett.jpg"]], "armas5": ["HimnodelasCumbres.webp","JuramentoporlaLibertad.webp","Objeto_Hoja_Afilada_Celestial.webp"], "armas4": ["Objeto_Espada_de_Favonius.webp","DeseoPonsoñoso.webp","Amenoma.webp"]},
    {"nombre": "Xingchiu",  "imagen": "Xingchiu.jpg", "region": "Liyue", "rol": "Sub dps", "elemento": "Hydro", "reacciones": "Derretidos/Electrocargados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "1500 ataque %, 1500 defensa %, 1000 vida %, 200 Recarga de Energía, 300 Maestría Elemental, 190 Daño crítico %, 80 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Tartaglia",  "imagen": "Tartaglia.jpg", "region": "Liyue", "rol": "Main dps", "elemento": "Hydro", "reacciones": "Derretidos/Congelados", "talentos": "Ataque Básico > Habilidad Elemental > Habilidad Definitiva", "estadisticas": "2000 ataque %, 1500 defensa %, 1000 vida %, 180 Recarga de Energía, 200 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Yelan",  "imagen": "Yelan.jpg", "region": "Liyue", "rol": "Sub dps", "elemento": "Hydro", "reacciones": "Congelados/Vaporizados", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "1500 ataque %, 1500 defensa %, 4000 vida %, 200 Recarga de Energía, 200 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Sangonomiya Kokomi",  "imagen": "Kokomi.jpg", "region": "Inazuma", "rol": "Healer", "elemento": "Hydro", "reacciones": "Florecimiento/Derretidos", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "1000 ataque %, 1500 defensa %, 4000 vida %, 180 Recarga de Energía, 250 Maestría Elemental, 180 Daño crítico %, 70 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Kamisato Ayato",  "imagen": "Ayato.jpg", "region": "Inazuma", "rol": "Main dps/Sub dps", "elemento": "Hydro", "reacciones": "Congelados/Vaporizados", "talentos": "Ataque Básico > Habilidad Definitiva > Habilidad Elemental", "estadisticas": "2000 ataque %, 1500 defensa %, 2000 vida %, 200 Recarga de Energía, 300 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Candace",  "imagen": "Candace.jpg", "region": "Sumeru", "rol": "Sub dps", "elemento": "Hydro", "reacciones": "Vaporizados", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 2000 vida %, 180 Recarga de Energía, 300 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Nilou", "imagen": "Nilou.jpg", "region": "Sumeru", "rol": "Sub dps", "elemento": "Hydro", "reacciones": "Florecimiento/Vaporizados", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "1500 ataque %, 1500 defensa %, 2000 vida %, 190 Recarga de Energía, 500 Maestría Elemental, 190 Daño crítico %, 80 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Neuvillette", "imagen": "Neuvillette.jpg", "region": "Fontaine", "rol": "Main dps", "elemento": "Hydro", "reacciones": "Florecimiento/Vaporizados/Congelados/Electrocargados", "talentos": "Ataque Básico > Habilidad Definitiva > Habilidad Elemental", "estadisticas": "2000 ataque %, 1500 defensa %, 4000 vida %, 200 Recarga de Energía, 300 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Furina", "imagen": "Furina.jpg", "region": "Fontaine", "rol": "Healer/Buffer/Sub dps", "elemento": "Hydro", "reacciones": "Electrocargados/Vaporizados", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 4000 vida %, 250 Recarga de Energía, 300 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Sigewinne", "imagen": "Sigewinne.jpg", "region": "Fontaine", "rol": "Healer", "elemento": "Hydro", "reacciones": "Congelados/Vaporizados", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "1500 ataque %, 1500 defensa %, 4000 vida %, 190 Recarga de Energía, 200 Maestría Elemental, 160 Daño crítico %, 60 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Mualani", "imagen": "Mualani.jpg", "region": "Mualani", "rol": "Main dps", "elemento": "Hydro", "reacciones": "Vaporizados/Electrocargados", "talentos": "Habilidad Elemental > Habilidad Definitiva > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 4000 vida %, 180 Recarga de Energía, 300 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Aino", "imagen": "Aino.jpg", "region": "Nod Krai", "rol": "Sub dps", "elemento": "Hydro", "reacciones": "Electrocargado Lunar/Florecimiento Lunar", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "1000 ataque %, 1500 defensa %, 1000 vida %, 200 Recarga de Energía, 1000 Maestría Elemental, 160 Daño crítico %, 60 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Colombina Hiposelenia", "imagen": "Colombina.jpg", "region": "Nod Krai", "rol": "Healer/Buffer", "elemento": "Hydro", "reacciones": "Electrocargado Lunar/Florecimiento Lunar", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 4000 vida %, 200 Recarga de Energía, 300 Maestría Elemental, 200 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
]


def HydroView(page: ft.Page, user: dict, on_volver=None):
    from views.pyros import _ElementoView
    return _ElementoView(page, user, on_volver, "Hydro", "#38bdf8", PERSONAJES)
