import flet as ft
from views.PersonajeDetalle import PersonajeDetalle

PERSONAJES = [ 
    {"nombre": "Barbara",  "imagen": "Barbara.jpg", "region": "Mondstadt", "rol": "Healer", "elemento": "Hydro", "reacciones": "Congelados/Derretidos", "talentos": "Habilidad Definitiva > Habilidad Elemental > Ataque Básico", "estadisticas": "2000 ataque %, 1500 defensa %, 1000 vida %, 160 Recarga de Energía, 200 Maestría Elemental, 300 Daño crítico %, 90 Probabilidad Crítica", "artefactos": ["PerlaOceanica.webp","PergaminoHeroe.webp","Instructor.webp"], "equipos": [["HuTao.jpg","Xiangling.jpg","Barbara.jpg","Venti.jpg"],["Klee.jpg","Xiangling.jpg","Barbara.jpg","Sacarosa.jpg"],["Razor.jpg","Beidou.jpg","Barbara.jpg","Sacarosa.jpg"]], "armas5": ["VigiadelasEstrellas.webp","MilNoches.webp","Hibernacion.webp"], "armas4": ["MemoriasdeSacrificios.webp","Laud.webp","CartaNautica.webp"]},
    {"nombre": "Mona",  "imagen": "Mona.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Dalhia",  "imagen": "Dahlia.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Xingchiu",  "imagen": "Xingchiu.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Tartaglia",  "imagen": "Tartaglia.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Yelan",  "imagen": "Yelan.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Sangonomiya Kokomi",  "imagen": "Kokomi.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Kamisato Ayato",  "imagen": "Ayato.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Candace",  "imagen": "Candace.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Nilou", "imagen": "Nilou.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Neuvillette", "imagen": "Neuvillette.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Furina", "imagen": "Furina.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Sigewinne", "imagen": "Sigewinne.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Mualani", "imagen": "Mualani.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Aino", "imagen": "Aino.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
    {"nombre": "Colombina Hiposelenia", "imagen": "Colombina.jpg", "region": "text", "rol": "", "elemento": "Hydro", "reacciones": "text", "talentos": "text", "estadisticas": "text", "artefactos": ["","",""], "equipos": [["","","",""],["","","",""],["","","",""]], "armas5": ["","",""], "armas4": ["","",""]},
]


def HydroView(page: ft.Page, user: dict, on_volver=None):
    from views.pyros import _ElementoView
    return _ElementoView(page, user, on_volver, "Hydro", "#38bdf8", PERSONAJES)
